[package]
name = "miden-crypto"
version = "0.7.1"
description = "Miden Cryptographic primitives"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/crypto"
documentation = "https://docs.rs/miden-crypto/0.7.1"
categories = ["cryptography", "no-std"]
keywords = ["miden", "crypto", "hash", "merkle"]
edition = "2021"
rust-version = "1.73"

[[bin]]
name = "miden-crypto"
path = "src/main.rs"
bench = false
doctest = false
required-features = ["executable"]

[[bench]]
name = "hash"
harness = false

[[bench]]
name = "smt"
harness = false

[[bench]]
name = "store"
harness = false

[features]
default = ["std"]
executable = ["dep:clap", "dep:rand_utils", "std"]
serde = ["dep:serde", "serde?/alloc", "winter_math/serde"]
std = ["blake3/std", "dep:cc", "dep:libc", "winter_crypto/std", "winter_math/std", "winter_utils/std"]
sve = ["std"]

[dependencies]
blake3 = { version = "1.5", default-features = false }
clap = { version = "4.4", features = ["derive"], optional = true }
libc = { version =  "0.2", default-features = false, optional = true }
rand_utils = { package = "winter-rand-utils", optional = true, git="https://github.com/lambdaclass/winterfell-for-lambdaworks", branch="derive-clone-v6.4" }
serde = { version = "1.0", features = [ "derive" ], default-features = false, optional = true }
winter_crypto = {  package = "winter-crypto", default-features = false, git="https://github.com/lambdaclass/winterfell-for-lambdaworks", branch="derive-clone-v6.4" }
winter_math = {  package = "winter-math", default-features = false, git="https://github.com/lambdaclass/winterfell-for-lambdaworks", branch="derive-clone-v6.4" }
winter_utils = { package = "winter-utils", default-features = false, git="https://github.com/lambdaclass/winterfell-for-lambdaworks", branch="derive-clone-v6.4" }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1.3"
rand_utils = {  package = "winter-rand-utils", git="https://github.com/lambdaclass/winterfell-for-lambdaworks", branch="derive-clone-v6.4" }

[build-dependencies]
cc = { version = "1.0", features = ["parallel"], optional = true }
glob = "0.3"
